### PR TITLE
fix run on android

### PR DESCRIPTION
**Pull request by nimr77**
this has a fix for building on android, and updating the plugin

### CODE REVIEW

**Comment by WebEferen** [comment]
Thank You @nimr77 for solving that particular issue.

**Comment by WebEferen** [comment]
As follow-up small task for myself:
- [ ] Create plugin example with new code examples.

**Comment by nimr77** [comment]
Thank you, I had to remove the example code just to run the app and test it on Android

**Comment by WebEferen** [comment]
No worries, had no idea that s1 still might be using the passkit so will bump it and update to match some of new Flutter 3.0 features such as Null safety etc.

**Comment by nimr77** [comment]
could you update the package on dart pub

**Comment by WebEferen** [comment]
Done, sorry for delay but the ci workflow was missing.
This week will update it to make it automatic :)

**Pull request merged**
